Config:
  only:
    - master
  image: rakudo-star
  before_script:
    - zef install . --deps-only --test-depends --/test
  script: AUTHOR_TESTING=1 prove -l
  artifacts:
    name: "raku-Config"
    paths:
      - META6.json
      - bin
      - lib
      - resources
      - t

test:
  except:
    - master
  image: rakudo-star
  before_script:
    - zef install . --deps-only --test-depends --/test
  script: AUTHOR_TESTING=1 prove -lv
