Config:
  only:
    - master
  image: registry.gitlab.com/tyil/docker-perl6:debian-dev-latest
  before_script:
    - zef install App::Prove6
    - zef install --deps-only --test-depends --/test .
  script: AUTHOR_TESTING=1 prove6 -l
  artifacts:
    name: "raku-Config"
    paths:
      - META6.json
      - bin
      - lib
      - resources
      - t

test:
  except:
    - master
  image: registry.gitlab.com/tyil/docker-perl6:debian-dev-latest
  before_script:
    - zef install App::Prove6
    - zef install . --deps-only --test-depends --/test
  script: AUTHOR_TESTING=1 prove6 -lv
