language: generic

env:
  global:
    - PATH=/opt/rakudo-pkg/bin:$PATH
  matrix:
    - VERSION=2019.03.1-03
    #- VERSION=2018.12-01 TAG=v2018.12
    - VERSION=2018.09-02
    - VERSION=2018.06-01
    - VERSION=2018.03-01

os:
  - linux

before_install:
  - cd $(mktemp -d)
  - wget "https://github.com/nxadm/rakudo-pkg/releases/download/${TAG:-v${VERSION}}/rakudo-pkg-Ubuntu16.04_${VERSION}_amd64.deb" && sudo dpkg -i *.deb
  - cd ${TRAVIS_BUILD_DIR}

install:
  - zef install --deps-only .

script: AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t/
